name: Jenetics Build

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: [25]
      fail-fast: false
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java-version }} on ${{ matrix.os }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'zulu'
        cache: 'gradle'
    - name: Build with Gradle
      run: ./gradlew build --stacktrace --info
    timeout-minutes: 150
